ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS username VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL DEFAULT '',
    MODIFY firstname VARCHAR(255) NOT NULL DEFAULT '',
    MODIFY lastname VARCHAR(255) NOT NULL DEFAULT ''
