DROP TABLE IF EXISTS TALK_PROJECT;
DROP TABLE IF EXISTS TALK_EVENT;
DROP TABLE IF EXISTS USER_MESSAGE;
DROP TABLE IF EXISTS MESSAGE_TALK;
DROP TABLE IF EXISTS USER_TALK;
DROP TABLE IF EXISTS CATEGORY_TALK;
