ALTER TABLE TALKS
    ADD COLUMN IF NOT EXISTS type VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description TEXT
